image: freebsd/latest
packages:
  - node8
  - npm-node8
  - postgresql10-client
  - postgresql10-server
  - py36-pip
  - py36-sqlite3
  - py36-virtualenv
  - python3
  - python36
  - yarn-node8
sources:
  - https://git.sr.ht/~sirn/fanboi2
tasks:
  - setup: |
      cd fanboi2/ || exit 1
      export PATH=$HOME/.local/bin:$PATH

      pip install --user poetry
      poetry install
      yarn install
      yarn run gulp
  - test: |
      cd fanboi2/ || exit 1
      export PATH=$HOME/.local/bin:$PATH

      sudo service postgresql oneinitdb
      sudo sysrc postgresql_enable=YES
      sudo sysrc postgresql_flags="-l /var/log/postgresql.log"
      (
        printf "local all all trust\\n"
        printf "host all all 127.0.0.1/32 trust\\n"
        printf "host all all ::1/128 trust\\n"
      ) | sudo tee /var/db/postgres/data10/pg_hba.conf

      sudo touch /var/log/postgresql.log
      sudo chown postgres /var/log/postgresql.log
      sudo service postgresql start
      trap "sudo service postgresql stop" 0 1 2 3 6 14 15
      sudo -u postgres createuser -ds fanboi2
      sudo -u postgres createdb -U fanboi2 fanboi2_test

      export POSTGRESQL_TEST_DATABASE="postgresql://fanboi2:@localhost:5432/fanboi2_test"
      poetry run nose2
