---
version: "3.4"

x-presets:
  fanboi2: &fanboi2
    image: sirn/fanboi2:latest
    restart: always
    networks:
      - fbnet
    depends_on:
      - postgres
      - redis
    environment:
      AUTH_SECRET: CHANGE_ME
      SESSION_SECRET: CHANGE_ME
      DATABASE_URL: postgresql://postgres:passw0rd@postgres:5432/fanboi2
      REDIS_URL: redis://redis/0
      CELERY_BROKER_URL: redis://redis/1

services:
  postgres:
    image: postgres:10.5-alpine
    restart: always
    volumes:
      - postgres-db:/var/lib/postgresql/data
      - ./scripts/initdb.sh:/docker-entrypoint-initdb.d/initdb.sh
    networks:
      - fbnet
    environment:
      DB_PASSWORD: passw0rd
    healthcheck:
      test: [CMD-SHELL, pg_isready, -U, postgres]
      interval: 30s
      retries: 3

  redis:
    image: redis:5.0-alpine
    restart: always
    volumes:
      - redis-db:/data
    networks:
      - fbnet
    healthcheck:
      test: [CMD-SHELL, redis-cli, ping]
      interval: 30s
      retries: 3

  web:
    <<: *fanboi2
    command:
      - serve
    ports:
      - "6543:6543"

  worker:
    <<: *fanboi2
    command: [worker]

  beat:
    <<: *fanboi2
    command: [beat]

  migrate:
    <<: *fanboi2
    restart: on-failure
    command: [migrate]

networks:
  fbnet:

volumes:
  postgres-db:
  redis-db:
