from setuptools import setup, find_packages


setup(
    name="fanboi2",
    version="2018.10",
    description="Board engine behind fanboi.ch",
    long_description="",
    classifiers=[
        "programming language :: python",
        "programming language :: python :: 3",
        "framework :: pyramid",
        "topic :: internet :: www/http",
        "topic :: internet :: www/http :: wsgi :: application",
    ],
    author="",
    author_email="",
    url="",
    keywords="web wsgi bfg pylons pyramid",
    packages=find_packages(),
    include_package_data=True,
    zip_safe=False,
    test_suite="fanboi2.tests",
    install_requires=[
        "alembic >=0.9, <0.10",
        "argon2_cffi",
        "celery >=4.1, <4.2",
        "dogpile.cache",
        "geoip2",
        "hiredis",
        "hupper",
        "isodate",
        "MarkupSafe",
        "misaka",
        "passlib",
        "psycopg2",
        "pyramid >=1.9, <1.10",
        "pyramid_debugtoolbar",
        "pyramid_mako",
        "pyramid_nacl_session",
        "pyramid_services",
        "pyramid_tm",
        "python3-memcached",
        "pytz",
        "redis",
        "requests",
        "sqlalchemy >=1.2, <1.3",
        "transaction",
        "waitress",
        "wtforms >=2.1, <3.0",
        "zope.sqlalchemy",
    ],
    test_requires=["coverage", "nose", "rednose"],
    python_requires=">=3.6",
    entry_points="""
    [console_scripts]
    fbctl = fanboi2.cmd.ctl:main
    fbcelery = fanboi2.cmd.celery:main
    """,
)
